kind: CivoKubernetes
apiVersion: cluster.civo.crossplane.io/v1alpha1
metadata: 
  name: test-crossplane
spec:
  name: test-crossplane
  instances: 3
  size: g3.k3s.small
  applications: 
    - "argo-cd"
    - "prometheus-operator"
  connectionDetails:
    connectionSecretNamePrefix: "cluster-details"
    connectionSecretNamespace: "default"
  providerConfigRef:
    name: civo-provider
