kind: CivoKubernetes
apiVersion: cluster.civo.crossplane.io/v1alpha1
metadata: 
  name: example-civo-cluster
spec:
  name: test-cluster
  instances: 2
  size: g3.k3s.small
  applications: 
    - "Flux"
    - "prometheus-operator"
  connectionDetails:
    connectionSecretNamePrefix: "cluster-details"
    connectionSecretNamespace: "default"
  providerConfigRef:
    name: civo-provider
